### ISSUE TITLE
Lấy nhiệm vụ từ 03 đợt liền kề để chuyển

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/Danh-gia-kqlv#11]
Hiển thị danh sách nhiệm vụ từ đợt trước lấy từ 03 đợt liền kề, hiện chỉ lấy 1 đợt 
![ảnh](https://user-images.githubusercontent.com/1935451/77628907-4820ef80-6f7b-11ea-9963-e40fbe604cc2.png)

**Comment by npbnguyen** [comment]
Đã xong!
