### ISSUE TITLE
Danh sách VB đi lấy theo đợt riêng đơn vị

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/Danh-gia-kqlv#13]
Danh sách VB đi lấy theo đợt đánh giá tháng của đơn vị, không lấy theo đợt riêng vì các đơn vị điều chỉnh đợt riêng rất nhiều

Lưu ý là dùng đợt riêng cho các WS khác của đơn vị nữa

**Comment by npbnguyen** [comment]
Resolved.
